-- ============================================================================
-- Superadmin / Contributor roles + approval workflow
-- Run this once in Supabase Dashboard -> SQL Editor
-- ============================================================================

-- 1. profiles ---------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'pending' check (role in ('pending','contributor','superadmin','rejected')),
  created_at timestamptz not null default now()
);

-- 2. pending_changes ----------------------------------------------------------
create table if not exists public.pending_changes (
  id bigint generated by default as identity primary key,
  target_table text not null check (target_table in ('Quesitons','Platforms','Questions Types')),
  target_id bigint,
  action text not null check (action in ('create','update','delete')),
  payload jsonb,
  previous jsonb,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  submitted_by uuid references auth.users(id) default auth.uid(),
  submitted_at timestamptz not null default now(),
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  review_note text
);

-- 3. helper functions (security definer so RLS policies don't recurse) ------
create or replace function public.is_superadmin() returns boolean
language sql security definer stable as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'superadmin');
$$;

create or replace function public.get_my_role() returns text
language sql security definer stable as $$
  select role from public.profiles where id = auth.uid();
$$;

-- 4. profiles RLS -------------------------------------------------------------
alter table public.profiles enable row level security;

drop policy if exists "view own profile or all if superadmin" on public.profiles;
create policy "view own profile or all if superadmin" on public.profiles
  for select using (id = auth.uid() or public.is_superadmin());

drop policy if exists "superadmin update profiles" on public.profiles;
create policy "superadmin update profiles" on public.profiles
  for update using (public.is_superadmin()) with check (public.is_superadmin());

drop policy if exists "superadmin delete profiles" on public.profiles;
create policy "superadmin delete profiles" on public.profiles
  for delete using (public.is_superadmin());

-- 5. pending_changes RLS -------------------------------------------------------
alter table public.pending_changes enable row level security;

drop policy if exists "contributors insert own pending changes" on public.pending_changes;
create policy "contributors insert own pending changes" on public.pending_changes
  for insert
  with check (submitted_by = auth.uid() and public.get_my_role() in ('contributor','superadmin'));

drop policy if exists "view own or all if superadmin" on public.pending_changes;
create policy "view own or all if superadmin" on public.pending_changes
  for select using (submitted_by = auth.uid() or public.is_superadmin());

-- No update/delete policy for clients on purpose — only the RPC functions
-- below (running as table owner) may change status.

-- 6. auto-create a profile row on signup --------------------------------------
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer as $$
begin
  insert into public.profiles (id, email, role) values (new.id, new.email, 'pending');
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 7. backfill: promote every existing auth user to superadmin -----------------
-- (safe today since your admin account is currently the only one; re-run
--  harmlessly later, it will just leave already-classified rows alone via
--  the WHERE guard below if you remove the update clause)
insert into public.profiles (id, email, role)
select id, email, 'superadmin' from auth.users
on conflict (id) do update set role = 'superadmin';

-- 8. tighten writes on the 3 content tables to superadmin-only ----------------
drop policy if exists "authenticated write platforms" on "Platforms";
drop policy if exists "superadmin write platforms" on "Platforms";
create policy "superadmin write platforms" on "Platforms" for all
  using (public.is_superadmin()) with check (public.is_superadmin());

drop policy if exists "authenticated write question types" on "Questions Types";
drop policy if exists "superadmin write question types" on "Questions Types";
create policy "superadmin write question types" on "Questions Types" for all
  using (public.is_superadmin()) with check (public.is_superadmin());

drop policy if exists "authenticated write questions" on "Quesitons";
drop policy if exists "superadmin write questions" on "Quesitons";
create policy "superadmin write questions" on "Quesitons" for all
  using (public.is_superadmin()) with check (public.is_superadmin());

-- 9. approve / reject RPCs ------------------------------------------------------
create or replace function public.approve_pending_change(p_id bigint, p_note text default null)
returns void
language plpgsql
security definer
as $$
declare
  v_change record;
begin
  if not public.is_superadmin() then
    raise exception 'Only superadmins can approve changes';
  end if;

  select * into v_change from public.pending_changes where id = p_id and status = 'pending';
  if v_change is null then
    raise exception 'Pending change % not found or already reviewed', p_id;
  end if;

  if v_change.target_table = 'Quesitons' then
    if v_change.action = 'create' then
      insert into "Quesitons"
        (title, questions, answer, code, solution_code, options, correct_answers, expected_output, hint, difficulty, platform_id, question_type_id, tags)
      values (
        v_change.payload->>'title', v_change.payload->>'questions', v_change.payload->>'answer',
        v_change.payload->>'code', v_change.payload->>'solution_code',
        v_change.payload->'options', v_change.payload->'correct_answers',
        v_change.payload->>'expected_output', v_change.payload->>'hint', v_change.payload->>'difficulty',
        (v_change.payload->>'platform_id')::bigint, (v_change.payload->>'question_type_id')::bigint,
        v_change.payload->>'tags'
      );
    elsif v_change.action = 'update' then
      update "Quesitons" set
        title = v_change.payload->>'title',
        questions = v_change.payload->>'questions',
        answer = v_change.payload->>'answer',
        code = v_change.payload->>'code',
        solution_code = v_change.payload->>'solution_code',
        options = v_change.payload->'options',
        correct_answers = v_change.payload->'correct_answers',
        expected_output = v_change.payload->>'expected_output',
        hint = v_change.payload->>'hint',
        difficulty = v_change.payload->>'difficulty',
        platform_id = (v_change.payload->>'platform_id')::bigint,
        question_type_id = (v_change.payload->>'question_type_id')::bigint,
        tags = v_change.payload->>'tags'
      where id = v_change.target_id;
    elsif v_change.action = 'delete' then
      delete from "Quesitons" where id = v_change.target_id;
    end if;

  elsif v_change.target_table = 'Platforms' then
    if v_change.action = 'create' then
      insert into "Platforms" ("Name", key, description, color)
      values (v_change.payload->>'Name', v_change.payload->>'key', v_change.payload->>'description', v_change.payload->>'color');
    elsif v_change.action = 'update' then
      update "Platforms" set
        "Name" = v_change.payload->>'Name',
        key = v_change.payload->>'key',
        description = v_change.payload->>'description',
        color = v_change.payload->>'color'
      where id = v_change.target_id;
    elsif v_change.action = 'delete' then
      delete from "Platforms" where id = v_change.target_id;
    end if;

  elsif v_change.target_table = 'Questions Types' then
    if v_change.action = 'create' then
      insert into "Questions Types" (name) values (v_change.payload->>'name');
    elsif v_change.action = 'update' then
      update "Questions Types" set name = v_change.payload->>'name' where id = v_change.target_id;
    elsif v_change.action = 'delete' then
      delete from "Questions Types" where id = v_change.target_id;
    end if;
  end if;

  update public.pending_changes
    set status = 'approved', reviewed_by = auth.uid(), reviewed_at = now(), review_note = p_note
    where id = p_id;
end;
$$;

create or replace function public.reject_pending_change(p_id bigint, p_note text default null)
returns void
language plpgsql
security definer
as $$
begin
  if not public.is_superadmin() then
    raise exception 'Only superadmins can reject changes';
  end if;

  update public.pending_changes
    set status = 'rejected', reviewed_by = auth.uid(), reviewed_at = now(), review_note = p_note
    where id = p_id and status = 'pending';
end;
$$;

grant execute on function public.approve_pending_change(bigint, text) to authenticated;
grant execute on function public.reject_pending_change(bigint, text) to authenticated;

-- 10. Realtime: allow the pending_changes table to stream postgres_changes ----
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'pending_changes'
  ) then
    alter publication supabase_realtime add table public.pending_changes;
  end if;
end $$;
