import fs from 'fs';
import path from 'path';

const markdownPath = path.resolve('src/data/senior_react_javascript_interview_questions_readme.md');
const outputPath = path.resolve('src/data/parsedQuestions.ts');

const markdownContent = fs.readFileSync(markdownPath, 'utf-8');

// Helper to generate generic answers for theory questions
const generateGenericAnswer = (question) => {
  return `This is a comprehensive answer to "${question}". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic.`;
};

const parsedData = {
  theory: [],
  outputPrediction: []
};

// 1. Extract Output Prediction Questions
const outputPredictionSectionIndex = markdownContent.indexOf('# Output Prediction Questions');
if (outputPredictionSectionIndex !== -1) {
  const outputContent = markdownContent.slice(outputPredictionSectionIndex);
  
  // Regex to match:
  // ## 1. Title
  // ```js
  // <code>
  // ```
  // Expected Output:
  // ```js
  // <output>
  // ```
  const regex = /## \d+\.\s+(.*?)\n+```js\n([\s\S]*?)```\n+Expected Output:\n+```js\n([\s\S]*?)```/g;
  
  let match;
  let id = 1;
  while ((match = regex.exec(outputContent)) !== null) {
    const title = match[1].trim();
    const code = match[2].trim();
    const expectedOutput = match[3].trim().split('\n').map(line => line.trim());
    
    // Scramble the output for the chips, ensuring it's not the exact same as expected
    let scrambledOutput = [...expectedOutput];
    if (scrambledOutput.length > 1) {
      for (let i = scrambledOutput.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [scrambledOutput[i], scrambledOutput[j]] = [scrambledOutput[j], scrambledOutput[i]];
      }
    } else {
      // If there's only 1 line, let's add some distractor options
      scrambledOutput.push('undefined', 'TypeError', 'ReferenceError');
    }
    
    // Remove duplicates from scrambled to make it cleaner
    scrambledOutput = [...new Set(scrambledOutput)];

    parsedData.outputPrediction.push({
      id: `op_${id++}`,
      title,
      code,
      expectedOutput,
      options: scrambledOutput
    });
  }
}

// 2. Extract Theory Questions (we'll grab JS and React ones)
const theoryRegex = /\d+\.\s+(What is.*?\?|Explain.*|Difference between.*)/gi;
let match;
let theoryId = 1;
const extractedTheory = new Set();

while ((match = theoryRegex.exec(markdownContent)) !== null) {
  const q = match[1].trim();
  if (!extractedTheory.has(q)) {
    extractedTheory.add(q);
    parsedData.theory.push({
      id: `th_${theoryId++}`,
      question: q,
      answer: generateGenericAnswer(q)
    });
  }
}

// Sort theory questions from basic to advanced
const basicKeywords = ['what is', 'difference between let', '== and ===', 'jsx', 'props', 'state', 'hoisting', 'callback', 'arrow function', 'template literal'];
const advancedKeywords = ['usememo', 'usecallback', 'generator', 'reconciliation', 'fiber', 'suspense', 'ssr', 'ssg', 'saga', 'thunk', 'currying', 'memoization', 'throttle', 'debounce', 'deep clone', 'custom hook', 'portals', 'error boundaries', 'lazy loading', 'code splitting', 'graphql', 'zustand', 'recoil', 'isr', 'middleware'];

const getScore = (q) => {
  const lowerQ = q.toLowerCase();
  let score = 50; // default medium
  if (basicKeywords.some(k => lowerQ.includes(k))) score -= 20;
  if (advancedKeywords.some(k => lowerQ.includes(k))) score += 40;
  return score;
};

parsedData.theory.sort((a, b) => getScore(a.question) - getScore(b.question));

// Write to file
const tsContent = `
// AUTOGENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/parseMarkdown.mjs

export interface OutputPredictionQuestion {
  id: string;
  title: string;
  code: string;
  expectedOutput: string[];
  options: string[];
}

export interface TheoryQuestion {
  id: string;
  question: string;
  answer: string;
}

export const outputPredictionQuestions: OutputPredictionQuestion[] = ${JSON.stringify(parsedData.outputPrediction, null, 2)};

export const theoryQuestions: TheoryQuestion[] = ${JSON.stringify(parsedData.theory, null, 2)};
`;

fs.writeFileSync(outputPath, tsContent, 'utf-8');
console.log('Successfully parsed questions to src/data/parsedQuestions.ts');
console.log(`Extracted \${parsedData.outputPrediction.length} Output Prediction questions.`);
console.log(`Extracted \${parsedData.theory.length} Theory questions.`);
