
// AUTOGENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/parseMarkdown.mjs

export interface OutputPredictionQuestion {
  id: string;
  title: string;
  code: string;
  expectedOutput: string[];
  options: string[];
}

export interface TheoryQuestion {
  id: string;
  question: string;
  answer: string;
}

export const outputPredictionQuestions: OutputPredictionQuestion[] = [
  {
    "id": "op_1",
    "title": "Event Loop Output",
    "code": "console.log(\"Start\");\n\nsetTimeout(() => {\n  console.log(\"Timeout\");\n}, 0);\n\nPromise.resolve().then(() => {\n  console.log(\"Promise\");\n});\n\nconsole.log(\"End\");",
    "expectedOutput": [
      "Start",
      "End",
      "Promise",
      "Timeout"
    ],
    "options": [
      "Promise",
      "Timeout",
      "End",
      "Start"
    ]
  },
  {
    "id": "op_2",
    "title": "var with setTimeout",
    "code": "for (var i = 0; i < 3; i++) {\n\n  setTimeout(() => {\n    console.log(i);\n  }, 1000);\n\n}",
    "expectedOutput": [
      "3",
      "3",
      "3"
    ],
    "options": [
      "3"
    ]
  },
  {
    "id": "op_3",
    "title": "let with setTimeout",
    "code": "for (let i = 0; i < 3; i++) {\n\n  setTimeout(() => {\n    console.log(i);\n  }, 1000);\n\n}",
    "expectedOutput": [
      "0",
      "1",
      "2"
    ],
    "options": [
      "2",
      "0",
      "1"
    ]
  },
  {
    "id": "op_4",
    "title": "Promise vs setTimeout",
    "code": "setTimeout(() => console.log(\"Timeout\"));\n\nPromise.resolve().then(() => console.log(\"Promise\"));\n\nconsole.log(\"Sync\");",
    "expectedOutput": [
      "Sync",
      "Promise",
      "Timeout"
    ],
    "options": [
      "Promise",
      "Sync",
      "Timeout"
    ]
  },
  {
    "id": "op_5",
    "title": "Hoisting Example",
    "code": "console.log(a);\n\nvar a = 10;",
    "expectedOutput": [
      "undefined"
    ],
    "options": [
      "undefined",
      "TypeError",
      "ReferenceError"
    ]
  },
  {
    "id": "op_6",
    "title": "TDZ Example",
    "code": "console.log(a);\n\nlet a = 10;",
    "expectedOutput": [
      "ReferenceError"
    ],
    "options": [
      "ReferenceError",
      "undefined",
      "TypeError"
    ]
  },
  {
    "id": "op_7",
    "title": "Closure Example",
    "code": "function outer() {\n\n  let count = 0;\n\n  return function inner() {\n    count++;\n    console.log(count);\n  };\n\n}\n\nconst counter = outer();\n\ncounter();\ncounter();\ncounter();",
    "expectedOutput": [
      "1",
      "2",
      "3"
    ],
    "options": [
      "3",
      "2",
      "1"
    ]
  },
  {
    "id": "op_8",
    "title": "call, apply, bind",
    "code": "const person = {\n  name: \"Anandu\"\n};\n\nfunction greet(city) {\n  console.log(this.name + \" from \" + city);\n}\n\ngreet.call(person, \"Doha\");",
    "expectedOutput": [
      "Anandu from Doha"
    ],
    "options": [
      "Anandu from Doha",
      "undefined",
      "TypeError",
      "ReferenceError"
    ]
  },
  {
    "id": "op_9",
    "title": "Async Await Output",
    "code": "async function test() {\n\n  console.log(1);\n\n  await Promise.resolve();\n\n  console.log(2);\n\n}\n\nconsole.log(3);\n\ntest();\n\nconsole.log(4);",
    "expectedOutput": [
      "3",
      "1",
      "4",
      "2"
    ],
    "options": [
      "3",
      "2",
      "4",
      "1"
    ]
  },
  {
    "id": "op_10",
    "title": "Promise Chain Output",
    "code": "Promise.resolve(1)\n  .then(res => {\n    console.log(res);\n    return res + 1;\n  })\n  .then(res => {\n    console.log(res);\n  });",
    "expectedOutput": [
      "1",
      "2"
    ],
    "options": [
      "1",
      "2"
    ]
  },
  {
    "id": "op_11",
    "title": "Function Hoisting Output",
    "code": "sayHello();\n\nfunction sayHello() {\n  console.log(\"Hello\");\n}",
    "expectedOutput": [
      "Hello"
    ],
    "options": [
      "Hello",
      "undefined",
      "TypeError",
      "ReferenceError"
    ]
  },
  {
    "id": "op_12",
    "title": "Function Expression Output",
    "code": "sayHello();\n\nvar sayHello = function () {\n  console.log(\"Hello\");\n};",
    "expectedOutput": [
      "TypeError"
    ],
    "options": [
      "TypeError",
      "undefined",
      "ReferenceError"
    ]
  },
  {
    "id": "op_13",
    "title": "this Keyword Output",
    "code": "const user = {\n  name: \"Anandu\",\n  greet() {\n    console.log(this.name);\n  }\n};\n\nuser.greet();",
    "expectedOutput": [
      "Anandu"
    ],
    "options": [
      "Anandu",
      "undefined",
      "TypeError",
      "ReferenceError"
    ]
  },
  {
    "id": "op_14",
    "title": "Array map Output",
    "code": "const arr = [1, 2, 3];\n\nconst data = arr.map(num => num * 2);\n\nconsole.log(data);",
    "expectedOutput": [
      "[2, 4, 6]"
    ],
    "options": [
      "[2, 4, 6]",
      "undefined",
      "TypeError",
      "ReferenceError"
    ]
  }
];

export const theoryQuestions: TheoryQuestion[] = [
  {
    "id": "th_17",
    "question": "Difference between state and props",
    "answer": "This is a comprehensive answer to \"Difference between state and props\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_21",
    "question": "Difference between `useState` and `useReducer`",
    "answer": "This is a comprehensive answer to \"Difference between `useState` and `useReducer`\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_31",
    "question": "What is hoisting?",
    "answer": "This is a comprehensive answer to \"What is hoisting?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_32",
    "question": "What is the Temporal Dead Zone (TDZ)?",
    "answer": "This is a comprehensive answer to \"What is the Temporal Dead Zone (TDZ)?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_33",
    "question": "What is a callback function?",
    "answer": "This is a comprehensive answer to \"What is a callback function?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_34",
    "question": "What is a closure?",
    "answer": "This is a comprehensive answer to \"What is a closure?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_35",
    "question": "What is lexical scope?",
    "answer": "This is a comprehensive answer to \"What is lexical scope?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_36",
    "question": "What is the event loop?",
    "answer": "This is a comprehensive answer to \"What is the event loop?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_37",
    "question": "What is the call stack?",
    "answer": "This is a comprehensive answer to \"What is the call stack?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_38",
    "question": "What is a Promise?",
    "answer": "This is a comprehensive answer to \"What is a Promise?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_39",
    "question": "What is Promise chaining?",
    "answer": "This is a comprehensive answer to \"What is Promise chaining?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_40",
    "question": "What is event delegation and why use it?",
    "answer": "This is a comprehensive answer to \"What is event delegation and why use it?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_41",
    "question": "What is `this` in JavaScript?",
    "answer": "This is a comprehensive answer to \"What is `this` in JavaScript?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_42",
    "question": "What is async/await?",
    "answer": "This is a comprehensive answer to \"What is async/await?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_44",
    "question": "What is a Polyfill?",
    "answer": "This is a comprehensive answer to \"What is a Polyfill?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_53",
    "question": "What is synchronous and asynchronous execution?",
    "answer": "This is a comprehensive answer to \"What is synchronous and asynchronous execution?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_55",
    "question": "What is event bubbling?",
    "answer": "This is a comprehensive answer to \"What is event bubbling?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_56",
    "question": "What is event capturing?",
    "answer": "This is a comprehensive answer to \"What is event capturing?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_60",
    "question": "What is React and why use it?",
    "answer": "This is a comprehensive answer to \"What is React and why use it?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_64",
    "question": "What is JSX?",
    "answer": "This is a comprehensive answer to \"What is JSX?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_65",
    "question": "What is prop drilling and how to avoid it?",
    "answer": "This is a comprehensive answer to \"What is prop drilling and how to avoid it?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_68",
    "question": "What is a Pure Component?",
    "answer": "This is a comprehensive answer to \"What is a Pure Component?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_71",
    "question": "What is batching in React updates?",
    "answer": "This is a comprehensive answer to \"What is batching in React updates?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_75",
    "question": "What is React.memo?",
    "answer": "This is a comprehensive answer to \"What is React.memo?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_77",
    "question": "Explain lifting state up",
    "answer": "This is a comprehensive answer to \"Explain lifting state up\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_79",
    "question": "What is Next.js?",
    "answer": "This is a comprehensive answer to \"What is Next.js?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_83",
    "question": "What is dynamic routing in Next.js?",
    "answer": "This is a comprehensive answer to \"What is dynamic routing in Next.js?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_84",
    "question": "What is Redux?",
    "answer": "This is a comprehensive answer to \"What is Redux?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_86",
    "question": "What is Redux Toolkit?",
    "answer": "This is a comprehensive answer to \"What is Redux Toolkit?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_87",
    "question": "Difference between local state and global state",
    "answer": "This is a comprehensive answer to \"Difference between local state and global state\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_1",
    "question": "Difference between `let`, `const`, and `var`",
    "answer": "This is a comprehensive answer to \"Difference between `let`, `const`, and `var`\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_2",
    "question": "Difference between `==` and `===`",
    "answer": "This is a comprehensive answer to \"Difference between `==` and `===`\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_3",
    "question": "Difference between `every()` and `some()`",
    "answer": "This is a comprehensive answer to \"Difference between `every()` and `some()`\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_4",
    "question": "Difference between `map()` and `forEach()`",
    "answer": "This is a comprehensive answer to \"Difference between `map()` and `forEach()`\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_5",
    "question": "Difference between `Promise.all()` and `Promise.race()`",
    "answer": "This is a comprehensive answer to \"Difference between `Promise.all()` and `Promise.race()`\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_6",
    "question": "Difference between shallow copy and deep copy",
    "answer": "This is a comprehensive answer to \"Difference between shallow copy and deep copy\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_7",
    "question": "Difference between synchronous and asynchronous execution",
    "answer": "This is a comprehensive answer to \"Difference between synchronous and asynchronous execution\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_8",
    "question": "Difference between function declaration and function expression",
    "answer": "This is a comprehensive answer to \"Difference between function declaration and function expression\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_9",
    "question": "Difference between `setTimeout` and `setInterval`",
    "answer": "This is a comprehensive answer to \"Difference between `setTimeout` and `setInterval`\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_10",
    "question": "Difference between `localStorage` and `sessionStorage`",
    "answer": "This is a comprehensive answer to \"Difference between `localStorage` and `sessionStorage`\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_11",
    "question": "Difference between event bubbling and event capturing",
    "answer": "This is a comprehensive answer to \"Difference between event bubbling and event capturing\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_12",
    "question": "Difference between `for...in` and `for...of`",
    "answer": "This is a comprehensive answer to \"Difference between `for...in` and `for...of`\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_13",
    "question": "Difference between `slice`, `splice`, and `substring`",
    "answer": "This is a comprehensive answer to \"Difference between `slice`, `splice`, and `substring`\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_14",
    "question": "Difference between mutable and immutable objects",
    "answer": "This is a comprehensive answer to \"Difference between mutable and immutable objects\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_15",
    "question": "Difference between `fetch` and `axios`",
    "answer": "This is a comprehensive answer to \"Difference between `fetch` and `axios`\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_18",
    "question": "Difference between absolute and relative positioning",
    "answer": "This is a comprehensive answer to \"Difference between absolute and relative positioning\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_19",
    "question": "Difference between client-side rendering and server-side rendering",
    "answer": "This is a comprehensive answer to \"Difference between client-side rendering and server-side rendering\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_22",
    "question": "Difference between class components and functional components",
    "answer": "This is a comprehensive answer to \"Difference between class components and functional components\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_23",
    "question": "Difference between Promises and async/await",
    "answer": "This is a comprehensive answer to \"Difference between Promises and async/await\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_24",
    "question": "Difference between deep comparison and shallow comparison",
    "answer": "This is a comprehensive answer to \"Difference between deep comparison and shallow comparison\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_25",
    "question": "Difference between React hooks and lifecycle methods",
    "answer": "This is a comprehensive answer to \"Difference between React hooks and lifecycle methods\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_26",
    "question": "Difference between controlled and uncontrolled components",
    "answer": "This is a comprehensive answer to \"Difference between controlled and uncontrolled components\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_28",
    "question": "Difference between map, filter, and reduce",
    "answer": "This is a comprehensive answer to \"Difference between map, filter, and reduce\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_29",
    "question": "Difference between null, undefined, and NaN",
    "answer": "This is a comprehensive answer to \"Difference between null, undefined, and NaN\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_30",
    "question": "Difference between call, apply, and bind",
    "answer": "This is a comprehensive answer to \"Difference between call, apply, and bind\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_46",
    "question": "Explain `bind`, `call`, and `apply`",
    "answer": "This is a comprehensive answer to \"Explain `bind`, `call`, and `apply`\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_47",
    "question": "Explain garbage collection in JavaScript",
    "answer": "This is a comprehensive answer to \"Explain garbage collection in JavaScript\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_48",
    "question": "Explain prototype and prototypal inheritance",
    "answer": "This is a comprehensive answer to \"Explain prototype and prototypal inheritance\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_49",
    "question": "Explain destructuring",
    "answer": "This is a comprehensive answer to \"Explain destructuring\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_50",
    "question": "Explain spread operator",
    "answer": "This is a comprehensive answer to \"Explain spread operator\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_51",
    "question": "Explain rest operator",
    "answer": "This is a comprehensive answer to \"Explain rest operator\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_52",
    "question": "Explain string methods:",
    "answer": "This is a comprehensive answer to \"Explain string methods:\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_54",
    "question": "Explain deep copy and shallow copy",
    "answer": "This is a comprehensive answer to \"Explain deep copy and shallow copy\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_61",
    "question": "Explain Virtual DOM",
    "answer": "This is a comprehensive answer to \"Explain Virtual DOM\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_62",
    "question": "Explain commonly used hooks",
    "answer": "This is a comprehensive answer to \"Explain commonly used hooks\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_63",
    "question": "Explain lifecycle methods",
    "answer": "This is a comprehensive answer to \"Explain lifecycle methods\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_66",
    "question": "Explain Context API",
    "answer": "This is a comprehensive answer to \"Explain Context API\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_67",
    "question": "Explain Redux",
    "answer": "This is a comprehensive answer to \"Explain Redux\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_76",
    "question": "Explain the `useEffect` hook",
    "answer": "This is a comprehensive answer to \"Explain the `useEffect` hook\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_85",
    "question": "Explain Redux data flow",
    "answer": "This is a comprehensive answer to \"Explain Redux data flow\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_16",
    "question": "Difference between `useMemo` and `useCallback`",
    "answer": "This is a comprehensive answer to \"Difference between `useMemo` and `useCallback`\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_43",
    "question": "What is memoization?",
    "answer": "This is a comprehensive answer to \"What is memoization?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_45",
    "question": "What is currying in JavaScript?",
    "answer": "This is a comprehensive answer to \"What is currying in JavaScript?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_57",
    "question": "What is debounce?",
    "answer": "This is a comprehensive answer to \"What is debounce?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_58",
    "question": "What is throttle?",
    "answer": "This is a comprehensive answer to \"What is throttle?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_59",
    "question": "What is GraphQL?",
    "answer": "This is a comprehensive answer to \"What is GraphQL?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_69",
    "question": "What is a custom hook?",
    "answer": "This is a comprehensive answer to \"What is a custom hook?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_70",
    "question": "What is reconciliation in React?",
    "answer": "This is a comprehensive answer to \"What is reconciliation in React?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_72",
    "question": "What is React Fiber?",
    "answer": "This is a comprehensive answer to \"What is React Fiber?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_73",
    "question": "What is lazy loading?",
    "answer": "This is a comprehensive answer to \"What is lazy loading?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_74",
    "question": "What is Suspense?",
    "answer": "This is a comprehensive answer to \"What is Suspense?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_78",
    "question": "What is reconciliation?",
    "answer": "This is a comprehensive answer to \"What is reconciliation?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_81",
    "question": "What is ISR?",
    "answer": "This is a comprehensive answer to \"What is ISR?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_82",
    "question": "What is code splitting in Next.js?",
    "answer": "This is a comprehensive answer to \"What is code splitting in Next.js?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_88",
    "question": "What is Redux Thunk?",
    "answer": "This is a comprehensive answer to \"What is Redux Thunk?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_89",
    "question": "What is Redux Saga?",
    "answer": "This is a comprehensive answer to \"What is Redux Saga?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_90",
    "question": "What is Zustand?",
    "answer": "This is a comprehensive answer to \"What is Zustand?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_91",
    "question": "What is Recoil?",
    "answer": "This is a comprehensive answer to \"What is Recoil?\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_20",
    "question": "Difference between SSG, SSR, and CSR in Next.js",
    "answer": "This is a comprehensive answer to \"Difference between SSG, SSR, and CSR in Next.js\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_27",
    "question": "Difference between debounce and throttle",
    "answer": "This is a comprehensive answer to \"Difference between debounce and throttle\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_80",
    "question": "Difference between SSG, SSR, and CSR",
    "answer": "This is a comprehensive answer to \"Difference between SSG, SSR, and CSR\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_92",
    "question": "Explain memoization in React",
    "answer": "This is a comprehensive answer to \"Explain memoization in React\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_93",
    "question": "Explain code splitting",
    "answer": "This is a comprehensive answer to \"Explain code splitting\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  },
  {
    "id": "th_94",
    "question": "Explain debounce and throttle practically",
    "answer": "This is a comprehensive answer to \"Explain debounce and throttle practically\". In an actual interview, you should explain the core concept, provide a brief example, and discuss any trade-offs or best practices related to the topic."
  }
];
